language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
- "3.7"
- "3.8"
- "3.8-dev"
- "nightly"
install:
- pip3 install .
- pip3 install -r requirements.txt
script:
- pytest --durations=0 -vv
after_success:
- ci/after_success.sh
before_install:
- openssl aes-256-cbc -K $encrypted_4f3b16254c24_key -iv $encrypted_4f3b16254c24_iv
  -in secret-files.tar.enc -out secret-files.tar -d
- tar xvf secret-files.tar
